### ISSUE TITLE
Play after pause fails in Chrome

### ISSUE THREAD

**Issue by ptrkcsk** [Rich-Harris/phonograph#3]
In Chrome, if a clip is paused, calling `play()` again does not play the clip, and throws the following error:

```
DOMException: Cannot decode detached ArrayBuffer
```

I tested this with Phonograph v1.5.0 on the following platforms:

- Chrome 62 on macOS 10.13 (👎)
- Chrome 62 on Android 8.1 (👎)
- Safari on macOS 11.2 (👍)
- Safari on iOS 11.2 (👍)

[Here's a Pen to demonstrate.](https://codepen.io/ptrkcsk/pen/eeWjpq)

**Comment by Rich-Harris** [comment]
Thank you! To cut a long story short you just saved me a lot of trouble 😀

**Comment by ptrkcsk** [comment]
Glad I could help!
